name: "invoice"
arch: "amd64"
platform: "linux"
version: "${VERSION}"
section: "default"
priority: "extra"
maintainer: "Henrique hello.henrique@proton.me"
description: "Manage your freelance projects elegantly"
homepage: "https://github.com/CommonBerry/invoice"
license: "GPLv3"
contents:
  - src: ./dist/invoice
    dst: /usr/bin/invoice
